[package]
name = "phonemirror"
version = "1.0.0"
edition = "2021"

[dependencies]
chrono = "0.4"

[target.'cfg(target_os = "macos")'.dependencies]
tray-item = "0.10"

[target.'cfg(target_os = "windows")'.dependencies]
tray-item = "0.10"

[target.'cfg(target_os = "linux")'.dependencies]
tray-item = { version = "0.10", features = ["ksni"] }